### ISSUE TITLE
Spell check README

### ISSUE THREAD

**Issue by tHinqa** [montanaflynn/toy-spelling-corrector#1]
Every git [repository] deserves an issue or two...

performent->performant

Actually just an excuse to let you know I'm writing an OCR specific spell corrector in Go. I'll let you know when I put it up -- if you like. 

Currently it is pretty fast: 36s for a 1.36 million word archive.org book (Cassell's Dictionary of Cookery (1892)). Check only takes about 3.7s. Same book with Aspell -a takes about 1m10s and gets very few substitutes correct. Apples and oranges, I know but I like to think I'm on the right track. Oh, and the "toy" takes 5.76+10.02 on my equally ancient core2 machine.

**Comment by montanaflynn** [comment]
The irony...

I'd love to be kept in the loop about your project, it seems like it's really performant  (I got it right this time) and I'd love to learn from it.

When you say:

> Oh, and the "toy" takes 5.76+10.02 on my equally ancient core2 machine.

I'm assuming you mean this toy spelling corrector, but I'm unsure of how much time it took, did you mean 15.78s or is it some other notation I'm unaware of?

**Comment by tHinqa** [comment]
Sorry for obfuscating the toy stuff.

My 5.76s is for your 270 word 13.77s run,
and 10.02s for the 400 word 24.17s run.

All really meaningless but since my machine is 2.33GHz (win32 xp
go1.51), I would guess yours is around 1GHz.

Haven't had a chance to study your code yet but hope to find time this
coming week. Will see if I can take up your challenge(s).

Will also put up a bit of my stuff to see if it piques some interest.
